package dev.modelarium.examples.el_farol_bar;

import dev.modelarium.examples.el_farol_bar.config.ElFarolBarSettings;
import dev.modelarium.examples.el_farol_bar.config.SettingsLoader;
import dev.modelarium.examples.el_farol_bar.entities.agents.ElFarolBarAgentGenerator;
import dev.modelarium.examples.el_farol_bar.entities.agents.prediction.FocalPredictorFactory;
import dev.modelarium.examples.el_farol_bar.entities.environment.ElFarolBarEnvironmentGenerator;
import modelarium.Config;
import modelarium.Model;
import modelarium.results.immutable.ReadOnlyResults;
import modelarium.scheduler.RandomOrderScheduler;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Modelarium implementation of W. Brian Arthur's El Farol Bar problem.
 *
 * <p>Each week agents independently predict attendance from public attendance history, act on their currently most
 * accurate focal predictor, and then observe the aggregate attendance generated by everybody's decisions.
 */
public final class ElFarolBarMain {
    private static final String CONFIG_RESOURCE =
            "dev/modelarium/examples/el_farol_bar/el-farol-bar-config.json";

    private ElFarolBarMain() {}

    public static void main(String[] args) {
        ElFarolBarSettings settings = SettingsLoader.loadElFarolBarConfig(CONFIG_RESOURCE);
        validateSettings(settings);

        Config config = Config
                .builder()
                .populationSize(settings.agents().populationSize())
                .tickCount(settings.modelSettings().numOfWeeks())
                .threadCount(settings.modelSettings().numOfCores())
                .areThreadsSynced(true)
                .agentGenerator(new ElFarolBarAgentGenerator(settings))
                .environmentGenerator(new ElFarolBarEnvironmentGenerator(settings))
                .scheduler(new RandomOrderScheduler())
                .seed(settings.modelSettings().seed())
                .build();

        Model model = new Model(config);
        model.run();

        ReadOnlyResults results = model.getResults();
        printSummary(results, settings);

        Path outputPath = results.export("modelarium-examples/output/el_farol_bar");
        System.out.println("Results exported to: " + outputPath.toAbsolutePath());
    }

    private static void printSummary(ReadOnlyResults results, ElFarolBarSettings settings) {
        int weekCount = settings.modelSettings().numOfWeeks();
        int threshold = settings.bar().crowdingThreshold();
        int burnIn = Math.min(settings.modelSettings().summaryBurnInWeeks(), weekCount);

        List<Integer> attendanceByWeek = aggregateAttendance(results, weekCount);
        List<Integer> postBurnInAttendance = attendanceByWeek.subList(burnIn, attendanceByWeek.size());

        double meanAttendance = postBurnInAttendance.stream()
                .mapToInt(Integer::intValue)
                .average()
                .orElse(Double.NaN);
        double attendanceStandardDeviation = populationStandardDeviation(postBurnInAttendance, meanAttendance);
        double activeForecastsAboveThreshold = activeForecastsAboveThreshold(results, burnIn, threshold);

        System.out.printf("El Farol summary after %d burn-in weeks:%n", burnIn);
        System.out.printf("  Mean attendance: %.2f (crowding threshold: %d)%n", meanAttendance, threshold);
        System.out.printf("  Attendance standard deviation: %.2f%n", attendanceStandardDeviation);
        System.out.printf(
                "  Active forecasts above threshold: %.1f%%%n",
                activeForecastsAboveThreshold * 100.0
        );
    }

    private static List<Integer> aggregateAttendance(ReadOnlyResults results, int weekCount) {
        List<Integer> attendanceByWeek = new ArrayList<>();
        for (int week = 0; week < weekCount; week++)
            attendanceByWeek.add(0);

        Map<String, Map<String, Map<String, List<Object>>>> allAgentLogs = results.agents().allLogs();
        for (Map<String, Map<String, List<Object>>> agentLogs : allAgentLogs.values()) {
            List<Object> attendingLog = agentLogs.get("decision").get("attending");
            for (int week = 0; week < attendingLog.size(); week++) {
                if (Boolean.TRUE.equals(attendingLog.get(week)))
                    attendanceByWeek.set(week, attendanceByWeek.get(week) + 1);
            }
        }

        return attendanceByWeek;
    }

    private static double activeForecastsAboveThreshold(ReadOnlyResults results, int burnIn, int threshold) {
        long forecasts = 0;
        long forecastsAboveThreshold = 0;

        Map<String, Map<String, Map<String, List<Object>>>> allAgentLogs = results.agents().allLogs();
        for (Map<String, Map<String, List<Object>>> agentLogs : allAgentLogs.values()) {
            List<Object> predictedAttendanceLog = agentLogs.get("decision").get("predicted_attendance");
            for (int week = burnIn; week < predictedAttendanceLog.size(); week++) {
                forecasts++;
                if ((Integer) predictedAttendanceLog.get(week) > threshold)
                    forecastsAboveThreshold++;
            }
        }

        if (forecasts == 0)
            return Double.NaN;

        return (double) forecastsAboveThreshold / forecasts;
    }

    private static double populationStandardDeviation(List<Integer> values, double mean) {
        if (values.isEmpty())
            return Double.NaN;

        double squaredDifferences = values.stream()
                .mapToDouble(value -> {
                    double difference = value - mean;
                    return difference * difference;
                })
                .sum();

        return Math.sqrt(squaredDifferences / values.size());
    }

    private static void validateSettings(ElFarolBarSettings settings) {
        if (settings.agents().populationSize() <= 0)
            throw new IllegalArgumentException("populationSize must be greater than 0");

        if (settings.agents().predictorsPerAgent() < 2)
            throw new IllegalArgumentException("predictorsPerAgent must be at least 2");

        if (settings.agents().predictorsPerAgent() > FocalPredictorFactory.bankSize())
            throw new IllegalArgumentException(
                    "predictorsPerAgent cannot exceed focal predictor bank size of " + FocalPredictorFactory.bankSize()
            );

        if (settings.bar().crowdingThreshold() < 0
                || settings.bar().crowdingThreshold() >= settings.agents().populationSize())
            throw new IllegalArgumentException(
                    "crowdingThreshold must be at least 0 and less than populationSize"
            );

        if (settings.modelSettings().numOfCores() <= 0)
            throw new IllegalArgumentException("numOfCores must be greater than 0");

        if (settings.modelSettings().numOfWeeks() <= 0)
            throw new IllegalArgumentException("numOfWeeks must be greater than 0");

        if (settings.modelSettings().summaryBurnInWeeks() < 0)
            throw new IllegalArgumentException("summaryBurnInWeeks must not be negative");

        if (settings.prediction().initialAttendanceHistory() == null
                || settings.prediction().initialAttendanceHistory().isEmpty())
            throw new IllegalArgumentException("initialAttendanceHistory must contain at least one value");

        for (int attendance : settings.prediction().initialAttendanceHistory()) {
            if (attendance < 0 || attendance > settings.agents().populationSize())
                throw new IllegalArgumentException(
                        "Every initial attendance value must be between 0 and populationSize"
                );
        }
    }
}
